repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -l -w
        language: system
        types: [go]
        exclude: |
          (?x)^(
              api/types/.*\.go|
              proto/.*\.pb\.go
          )$

      - id: go-imports
        name: go imports
        entry: goimports -l -w
        language: system
        types: [go]
        exclude: |
          (?x)^(
              api/types/.*\.go|
              proto/.*\.pb\.go
          )$
