apiVersion: v1
kind: Service
metadata:
  name: platform-service
spec:
  selector:
    app: platform-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9008
      targetPort: 9008
    - name: metrics
      port: 8081
      targetPort: 8081
  type: LoadBalancer
